### PR TITLE
Added Watermark (credits) 2 

### PR DESCRIPTION
**Pull request by NajmAjmal-old**
Fixed this issue as well https://github.com/SintcoLTD/music-player/pull/3

### CODE REVIEW

**Comment by sulaymaanajmal** [comment]
That's a pretty nice update.

**Comment by sulaymaanajmal** [comment]
That's a pretty nice update.

**Review by sulaymaanajmal — COMMENTED** [review]
Nice update, good ui

**Comment by NajmAjmal** [comment]
Thanks!

**Pull request merged**
